public class ManagerA {
    public void doWork() {
        ManagerB mb = new ManagerB();
        mb.callbackA();
        // dummy logic 0
        // dummy logic 1
        // dummy logic 2
        // dummy logic 3
        // dummy logic 4
        // dummy logic 5
        // dummy logic 6
        // dummy logic 7
        // dummy logic 8
        // dummy logic 9
        // dummy logic 10
        // dummy logic 11
        // dummy logic 12
        // dummy logic 13
        // dummy logic 14
        // dummy logic 15
        // dummy logic 16
        // dummy logic 17
        // dummy logic 18
        // dummy logic 19
        // dummy logic 20
        // dummy logic 21
        // dummy logic 22
        // dummy logic 23
        // dummy logic 24
        // dummy logic 25
        // dummy logic 26
        // dummy logic 27
        // dummy logic 28
        // dummy logic 29
        // dummy logic 30
        // dummy logic 31
        // dummy logic 32
        // dummy logic 33
        // dummy logic 34
        // dummy logic 35
        // dummy logic 36
        // dummy logic 37
        // dummy logic 38
        // dummy logic 39
        // dummy logic 40
        // dummy logic 41
        // dummy logic 42
        // dummy logic 43
        // dummy logic 44
        // dummy logic 45
        // dummy logic 46
        // dummy logic 47
        // dummy logic 48
        // dummy logic 49
        // dummy logic 50
        // dummy logic 51
        // dummy logic 52
        // dummy logic 53
        // dummy logic 54
        // dummy logic 55
        // dummy logic 56
        // dummy logic 57
        // dummy logic 58
        // dummy logic 59
        // dummy logic 60
        // dummy logic 61
        // dummy logic 62
        // dummy logic 63
        // dummy logic 64
        // dummy logic 65
        // dummy logic 66
        // dummy logic 67
        // dummy logic 68
        // dummy logic 69
        // dummy logic 70
        // dummy logic 71
        // dummy logic 72
        // dummy logic 73
        // dummy logic 74
        // dummy logic 75
        // dummy logic 76
        // dummy logic 77
        // dummy logic 78
        // dummy logic 79
        // dummy logic 80
        // dummy logic 81
        // dummy logic 82
        // dummy logic 83
        // dummy logic 84
        // dummy logic 85
        // dummy logic 86
        // dummy logic 87
        // dummy logic 88
        // dummy logic 89
        // dummy logic 90
        // dummy logic 91
        // dummy logic 92
        // dummy logic 93
        // dummy logic 94
        // dummy logic 95
        // dummy logic 96
        // dummy logic 97
        // dummy logic 98
        // dummy logic 99
    }
    public void callbackB() {
        // End cycle
    }
}
